### ISSUE TITLE
Not yet able to sink from Kafka to MQTT

### ISSUE THREAD

**Issue by nguyenhongphu** [SINTEF-9012/kafka-mqtt-sink-connector#1]
Very good work on these connectors! 
Maybe I got my local configurations wrong which caused errors in WorkerSinkTask
So after having done until the step when I tried to publish a test message from Kafka: 
kafka-console-producer.sh --broker-list 127.0.0.1:9092 --topic test
>{"Hello": "World!", "topic":"test"}
>

There is this error message from the Kafka connect-distributed

[2020-04-20 22:48:31,099] ERROR WorkerSinkTask{id=mqtt-sink-connector3-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:488)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:465)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:359)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:86)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:488)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	... 13 more
[2020-04-20 22:48:31,104] ERROR WorkerSinkTask{id=mqtt-sink-connector3-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)

**Comment by brice-morin** [comment]
OK, you need to add `"value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter"` when registering the connector in the curl POST request. I guess this is needed for the hello world example, but may not be needed in general

**Comment by nguyenhongphu** [comment]
Perfect! Many thanks :-)
